server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_management_system
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Settings
application.jwt.secret=my-super-secret-key-for-inventory-management-system-12345
application.jwt.expiration=86400000

logging.level.org.hibernate=DEBUG